# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=4000)),
                ('question_title', models.CharField(max_length=2000)),
                ('input', models.CharField(default=0, max_length=5000)),
                ('correct_op', models.CharField(default=0, max_length=10000)),
                ('explanation', models.CharField(max_length=7000)),
                ('test_input', models.CharField(max_length=700)),
                ('test_output', models.CharField(max_length=10000)),
                ('cost', models.IntegerField()),
                ('type', models.CharField(default='Easy', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=10)),
                ('question_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round2.Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=100)),
                ('phone_number1', models.IntegerField()),
                ('phone_number2', models.IntegerField()),
                ('college_name1', models.CharField(max_length=100)),
                ('college_name2', models.CharField(max_length=100)),
                ('user_name1', models.CharField(max_length=100)),
                ('user_name2', models.CharField(max_length=100)),
                ('email1', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=100)),
                ('easy_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='user_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round2.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(null=True, through='round2.Score', to='round2.User'),
        ),
    ]
