# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
