# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='users',
            new_name='user',
        ),
    ]
