# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0002_question_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_op',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
