# Generated by Django 2.1.5 on 2019-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0003_auto_20171223_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_input',
            field=models.CharField(max_length=100000),
        ),
    ]
