# Generated by Django 2.1.5 on 2019-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0004_auto_20190224_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='language_prefered',
            field=models.CharField(default='c', max_length=50),
            preserve_default=False,
        ),
    ]
