# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0005_auto_20170103_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.TextField(),
        ),
    ]
