# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0006_auto_20170103_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(default=0, max_length=7000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
