# Generated by Django 2.1.5 on 2019-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0007_auto_20190227_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='language_preferred',
            field=models.CharField(default='c', max_length=50),
        ),
    ]
