# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0007_auto_20170103_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_input',
            field=models.CharField(default=0, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='test_output',
            field=models.IntegerField(default=0),
        ),
    ]
