# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0008_auto_20170106_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=4000),
        ),
    ]
