# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0009_auto_20170106_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_output',
            field=models.CharField(max_length=700),
        ),
    ]
