# Generated by Django 2.1.5 on 2019-02-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0009_auto_20190227_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_input',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_output',
            field=models.TextField(max_length=10000),
        ),
    ]
