# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0010_auto_20170106_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_op',
            field=models.CharField(default=0, max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_output',
            field=models.CharField(max_length=10000),
        ),
    ]
