# Generated by Django 2.1.5 on 2019-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0010_auto_20190228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(max_length=7000),
        ),
    ]
