# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0011_auto_20170106_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=100),
        ),
    ]
