# Generated by Django 2.1.5 on 2019-03-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0011_auto_20190228_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='input',
            field=models.CharField(default=0, max_length=10000),
        ),
    ]
