# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0012_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buyed_questions',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
