# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0014_question_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(to='round2.User'),
        ),
    ]
