# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0015_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(null=True, to='round2.User'),
        ),
    ]
