# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0016_auto_20171216_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='buyed_questions',
        ),
    ]
