# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0018_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='easy_counter',
            field=models.IntegerField(default=0),
        ),
    ]
