# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0019_user_easy_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(null=True, through='round2.Score', to='round2.User'),
        ),
        migrations.AddField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round2.Question'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round2.User'),
        ),
    ]
