# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0020_auto_20171216_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='users',
        ),
    ]
