# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0022_auto_20171216_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(null=True, through='round2.Score', to='round2.User'),
        ),
    ]
