# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0025_auto_20171216_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='question_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round2.Question'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round2.User'),
        ),
    ]
